name: ex1 - manual job

on:
  workflow_dispatch: # MANUAL TRIGGER

jobs:
  display-env-info:
    runs-on: ubuntu-latest
    name: Display Environment Information
    steps:
      - name: Display System Info
        run: |
          echo "Running job on:"
          echo ${{ runner.os }}
