name: ex2 - scheduled job

on:
  schedule:
    - cron: "4 5 * * *"
    workflow_dispatch: # MANUAL TRIGGER

jobs:
  display-current-date:
    runs-on: ubuntu-latest
    steps: |
          echo "Current date"
          echo $(date +'%Y-%m-%dT%H-%M-%S')
